### ISSUE TITLE
README muss erweitert werden

### ISSUE THREAD

**Issue by Akeshihiro** [KirstenWesker/Softwareprojekt---React.JS-Team#4]
Hier fällt mir nix dolles ein, haut einfach irgendwas.

**Comment by KrayZeee** [comment]
oof, das project hier hab ich schon komplett vergessen.
wie gehts euch so?

**Comment by KirstenWesker** [comment]
Hey, mir geht's gut soweit. Schreibe Grad meine Masterarbeit in Intelligente Systeme. Und wie läuft's bei dir?KirstenAm 18.01.2021 19:03 schrieb Toni <notifications@github.com>:
oof, das project hier hab ich schon komplett vergessen.
wie gehts euch so?

**Comment by KrayZeee** [comment]
mir gehts auch ganz gut.
Human malware macht alles ein wenig Interessanter im leben da man nie weiß was einen erwartet^^

**Comment by Akeshihiro** [comment]
Haha, da räumt man alte issues und sonstiges Gedöns auf und dann schreiben Leute, wie nice :rofl: Aber auch bei mir is alles gut, Arbeit läuft gut und auch sonst gehts voran :smile_cat:
